# Informative: Example of a caller workflow calling a reusable workflow located in a different repo 

# TODO: Use github.event.schedule to get the precise cron expression that triggered the workflow
name: Example Caller Workflow 1 (Print msg via calling another repo's workflow)

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        defined_var: 
            description: "Variable you want to be in the resulting string"
            required: false
            type: string

jobs:
  # Call reusable-workflow-1-print-msg from mcummings128/reusable-workflow-github-actions repo.
  call-reusable-workflow-1:
    # runs-on: ubuntu-latest
    name: Call mcummings128/reusable-workflow-1... workflow
    # NOTICE that when you call this manually, it will say the event was workflow_dispatch. Remember the workflow being called (see next line)
    # is located in another repo, so it might be surprising this isn't workflow_call. This is because (see next line)
    # The 'github' context will always reference the caller workflow's repository (this workflow is the caller workflow, and we call the workflow below (see next line)
    # manually via workflow_dispatch, which is why you see that as the listed event
    uses: mcummings128/reusable-workflow-github-actions/.github/workflows/reusable-workflow-1-print-msg.yml@a0ac798420e899465ccf75d80cb6625f106f2726
    # ???
    # permissions:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}