name: Github API Tests
# TODO: Have a trigger event here? Or in another action
# ex. on: schedule: cron: [Every first Tuesday of the month]
# TODO: Also use status check functions like success()
#TODO: Also in a separate action, show how uses and with work
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # 8-28-25: These should probably be commented back in at some point, but I'm doing PR related testing and this is just static.
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # workflow_dispatch allows you to run this workflow manually from the Actions tab
  # It can also be used from the Github API for external applications/scripts to trigger a workflow
  # The inputs context allows you to put in inputs when you run a workflow manually (reference via github.event.inputs)
  # They will appear when you hit the 'Run Workflow' buttons on the Action page, in a pop-up form format
  # Inputs can be customized into types to be required and have default values (see below for an example of each input type)
  # When a workflow is triggered (i.e. NOT manually), these inputs will be null if referenced.
  workflow_dispatch:
    inputs:
      calls:
        description: "Endpoint to call"
        required: true
        type: choice
        options:
          - Manually trigger test-action
          - Manually trigger with args test-action
          - Call the get labels endpoint
  
jobs:
  execute-api-call:
    name: Execute API call
    runs-on: ubuntu-latest
    steps:

      - name: Echo call value
        run: Triggering the call for "${{ inputs.calls }}"